kind: Pod
apiVersion: v1
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:stable-otel

# this YAML configuration tells Kubernetes to create a Pod with an Nginx container using a stable version of the Nginx image with OpenTelemetry integration.