kind: Pod
apiVersion: v1
metadata:
  name: env-test
spec:
  containers:
  - name: nginx
    image: nginx
    env:
    - name: course
      value: 'kubernetes'
    - name: duration
      value: '20hours'


# this YAML file creates a Pod that runs an Nginx container, 
# with two environment variables (course and duration) available to the container. 
# This helps configure the container's behavior without needing to modify the code.