kind: Pod
apiVersion: v1
metadata:
  name: resources
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      # soft limit
      requests:
        cpu: "100m"
        memory: "128Mi"
      # limits should be atleast or more than requests i.e hard limit
      limits:
        cpu: "100m"
        memory: "128Mi"


# Requests: Minimum resources guaranteed.
# Limits: Maximum resources allowed

# A container will always be guaranteed the requested resources, but it can use more if available (up to the limits).
# However, setting requests equal to limits means the container can't use more resources than allocated.






