apiVersion: v1
kind: Pod
metadata:
  name: pod-config
spec:
  containers:
  - name: nginx
    image: nginx
    envFrom:
    - configMapRef:
        name: devops
    # env:
    # - name: course
    #   valueFrom:
    #     configMapKeyRef:
    #       name: devops
    #       key: course
    # - name: trainer
    #   valueFrom:
    #     configMapKeyRef:
    #       name: devops
    #       key: trainer



This YAML sets up a Pod named pod-config with a container running the nginx image. 
The container gets its environment variables from the devops ConfigMap, making configuration management easier and more flexible.

envFrom: A keyword used to populate environment variables in a container from a ConfigMap or Secret.

ConfigMap: The ConfigMap named devops contains key-value pairs (like course and trainer) 
           that are used as environment variables in the container instead of hardcoding them.