apiVersion: v1
kind: Secret
metadata:
  name: pod-secret
data:
  username: "YWRtaW4K"
  password: "YWRtaW4xMjMK"


# This YAML defines a Kubernetes Secret named pod-secret. The data field contains two keys: 
#    username and password. These values are base64 encoded, meaning the original values are hidden for security purposes.

# For example:

# The base64 encoded username "YWRtaW4K" corresponds to "admin" when decoded.
# The base64 encoded password "YWRtaW4xMjMK" corresponds to "admin123" when decoded.
# Secrets in Kubernetes are used to store sensitive information like passwords, API keys, and tokens securely.