apiVersion: v1
kind: Pod
metadata:
  name: pod-secrets
spec:
  containers:
  - name: nginx
    image: nginx
    envFrom:
    - secretRef:
        name: pod-secret


# This YAML file sets up a Pod named pod-secrets that runs an NGINX container. 
# It pulls environment variables from a Secret called pod-secret, ensuring sensitive information is managed securely.