apiVersion: v1
kind: Service
metadata:
  name: nginx-np
spec:
  type: NodePort
  selector:
    name: frontend
    project: expense
    component: frontend
    environment: dev
  ports:
  - protocol: TCP
    port: 80 #service-port
    targetPort: 80 #target-port
    nodePort: 32760



# port: 80: The port that the service will listen to.
# targetPort: 80: The port on the pod that the service forwards traffic to.
# nodePort: 32760: The external port on the node where this service can be accessed.
# In short, this configuration exposes the frontend component of the expense project, 
# making it accessible from outside the Kubernetes cluster at port 32760 on any node.